version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: presenca_db
    environment:
      POSTGRES_DB: sistema_presenca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./presenca-system
    container_name: presenca_backend
    ports:
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sistema_presenca
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APP_FRONTEND_URL=http://localhost:8080
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=1025
    depends_on:
      - db
      - mailhog

  frontend:
    build:
      context: ./sitema-controle-presenca
    container_name: presenca_frontend
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend

  mailhog:
    image: mailhog/mailhog
    container_name: presenca_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data: